# image will be published to ghcr.io/<user>/<name>
name: tkkos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    snippets:
      - "wget --tries=10 https://raw.githubusercontent.com/ivan-hc/AM/main/APP-MANAGER -O /usr/local/bin/appman && chmod a+x /usr/local/bin/appman"
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-41.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-41.noarch.rpm
      - https://copr.fedorainfracloud.org/coprs/deltacopy/darkly/repo/fedora-41/deltacopy-darkly-fedora-41.repo
      # - https://copr.fedorainfracloud.org/coprs/luisbocanegra/kde-material-you-colors/repo/fedora-41/luisbocanegra-kde-material-you-colors-fedora-41.repo
    install:
        # CLI Tools:
        - zsh
        - exa
        - adb
        - trash-cli
        - btop
        - zoxide

        # Networking
        - tailscale

        # Development
        - vim
        - neovim
        - git
        - distrobox
        - docker
        - podman

        # Looks
        - darkly
        # - kde-material-you-colors

        # Drivers
        - kernel-modules-extra
        # - xorg-x11-drv-nvidia
        # - kmod-nvidia
    remove:
        - firefox
        - firefox-langpacks
       # Any packages included in the orignial distribution that should not be included in TKKOS go here

  - type: default-flatpaks
    notify: false # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
         - org.libreoffice.LibreOffice
         - org.kde.gwenview
    user:
      install: 
         - io.github.zen_browser.zen
         - com.vscodium.codium
         - com.borgbase.Vorta
         - net.lutris.Lutris
         - org.libreoffice.LibreOffice
         - com.obsproject.Studio
         - org.prismlauncher.PrismLauncher
  - type: systemd
    system:
      enabled:
        - tailscaled
      disabled:
        #- flatpak-system-update.timer
    user:
      enabled:
        #- 
      disabled:
        #- flatpak-user-update.timer
  # - type: chezmoi
  #   repository: "https://gitlab.com/TKK13909/tkkos-dotfiles"
  #   all-users: true
  #   #file-conflict-policy: replace
  #   run-every: 1h

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

